import pandas as pd
import numpy as np
import os

def run_data_engineering(file_path):
    print("🚀 Step 1: Initializing Data Engineering & Unpivoting...")
    
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Could not find {file_path}. Please verify the file location.")
        
    # Read the raw spreadsheet
    df = pd.read_csv(file_path)
    
    # Programmatically filter out the 'Total' summary row to prevent severe statistical outliers
    df = df[df['State/UT'].str.lower() != 'total'].dropna(subset=['State/UT'])
    
    # Normalize truncated regional strings for professional schema modeling
    state_mapping = {
        'Uttar Prad': 'Uttar Pradesh',
        'Madhya P': 'Madhya Pradesh',
        'Uttrakhan': 'Uttarakhand'
    }
    df['State/UT'] = df['State/UT'].replace(state_mapping)
    
    # Melt the horizontal metrics into structured chronological records
    records = []
    for idx, row in df.iterrows():
        state = row['State/UT']
        
        # Parse RMS 2022- (Assuming Qty is index 2, Value is index 3)
        records.append({
            'State': state, 'Financial_Year': 2022, 
            'Procurement_Qty_Lakh_MT': float(row.iloc[2]), 'Value_Rs_Crores': float(row.iloc[3])
        })
        # Parse RMS 2023- (Qty index 4, Value index 5)
        records.append({
            'State': state, 'Financial_Year': 2023, 
            'Procurement_Qty_Lakh_MT': float(row.iloc[4]), 'Value_Rs_Crores': float(row.iloc[5])
        })
        # Parse RMS 2024- (Qty index 6, Value index 7)
        records.append({
            'State': state, 'Financial_Year': 2024, 
            'Procurement_Qty_Lakh_MT': float(row.iloc[6]), 'Value_Rs_Crores': float(row.iloc[7])
        })
        
    normalized_df = pd.DataFrame(records)
    print(f"✅ Wide matrix successfully unpivoted into {normalized_df.shape[0]} relational records.")
    return normalized_df
def run_feature_engineering(df):
    print("\n🚀 Step 2: Executing Feature Engineering & Autoregressive Lags...")
    
    # Sort chronologically within geographic blocks to enforce strict timeline boundaries
    df = df.sort_values(by=['State', 'Financial_Year']).reset_index(drop=True)
    
    # Build the temporal lag variable (t-1 quantity) to model baseline dependencies
    df['Lag_1_Qty'] = df.groupby(['State'])['Procurement_Qty_Lakh_MT'].shift(1)
    
    # Drop the initial historical baseline rows containing NaN values generated by shifting
    processed_df = df.dropna().reset_index(drop=True)
    
    print("✅ Temporal engineering complete. Autoregressive feature ['Lag_1_Qty'] initialized.")
    return processed_df
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

def train_predictive_model(df):
    print("\n🚀 Step 3: Training Non-Linear Ensemble Architecture...")
    
    # Convert categorical state entities into binary indicators safely
    X = pd.get_dummies(df[['State', 'Financial_Year', 'Lag_1_Qty']], drop_first=True)
    y = df['Procurement_Qty_Lakh_MT']
    
    # Train-test split (using a controlled seed for reproducibility)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Fit the ensemble model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    
    # Metrics calculation
    predictions = model.predict(X_test)
    r2 = r2_score(y_test, predictions)
    print(f"✅ Model Training Complete. Explanatory Variance (R^2 Score): {r2:.4f}")
    
    # Extract structural feature weights
    print("\n--- Feature Importance Coefficients ---")
    for name, score in zip(X.columns, model.feature_importances_):
        if 'Lag_1_Qty' in name or score > 0.01:
            print(f"• {name}: {score:.4f}")
            
    return model, X_test, y_test, predictions
if __name__ == "__main__":
    CSV_PATH = "paddy_procurement.csv"
    
    try:
        raw_normalized = run_data_engineering(CSV_PATH)
        engineered_data = run_feature_engineering(raw_normalized)
        model, X_test, y_test, preds = train_predictive_model(engineered_data)
        print("\n🎉 Core Pipeline Executed Successfully!")
    except Exception as e:
        print(f"\n❌ Pipeline failed during execution: {str(e)}")
